---
development:
  cloud_name: dudvseir8
  api_key: '852814659885126'
  api_secret: plZhh3lTTOsBHSil_-9aMp86PuE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dudvseir8
  api_key: '852814659885126'
  api_secret: plZhh3lTTOsBHSil_-9aMp86PuE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dudvseir8
  api_key: '852814659885126'
  api_secret: plZhh3lTTOsBHSil_-9aMp86PuE
  enhance_image_tag: true
  static_image_support: false
