development:
  adapter: postgresql
  encoding: unicode
  database: rezepte
  pool: 20
  host: localhost
  username: rezepte
  password: rezepte

production:
  adapter: postgresql
  encoding: unicode
  database: rezepte
  pool: 50
  host: localhost
  username: rezepte
  password: rezepte