development:
  adapter: postgresql
  encoding: unicode
  database: rezepte
  pool: 2
  username: rezepte
  password: rezepte

production:
  adapter: postgresql
  encoding: unicode
  database: rezepte
  pool: 5
  username: rezepte
  password: rezepte